export { useActiveSchool } from "./useActiveSchool";
export { useStudents } from "./useStudents";
export { useClasses } from "./useClasses";
export { useAttendance } from "./useAttendance";
export { useMarks } from "./useMarks";
export { useTeachers } from "./useTeachers";
export { useDashboard, useSeed } from "./useDashboard";
export { useDebounce } from "./useDebounce";
export { useAuth } from "./useAuth";
export type { Role, RegisterInput } from "./useAuth";
export { useRegistrations } from "./useRegistrations";
