export { apiClient, ApiError } from "./client";
export { authRestApi } from "./auth";
export { studentsRestApi } from "./students";
export { teachersRestApi } from "./teachers";
export { classesRestApi } from "./classes";
export { attendanceRestApi } from "./attendance";
export { marksRestApi } from "./marks";
export { feesRestApi } from "./fees";
export { timetableRestApi, DAYS, PERIODS } from "./timetable";
export { notificationsRestApi } from "./notifications";
export { dashboardRestApi } from "./dashboard";
export { schoolsRestApi } from "./schools";
export { seedApi } from "./seed";
export { superAdminRestApi } from "./registrations";
export { accountRestApi } from "./account";
export { resultsRestApi } from "./results";
