export { apiClient, ApiError } from "./client";
export { authApi, authRestApi } from "./auth";
export { studentsApi, studentsRestApi } from "./students";
export { teachersApi, teachersRestApi } from "./teachers";
export { classesApi, classesRestApi } from "./classes";
export { attendanceApi, attendanceRestApi } from "./attendance";
export { marksApi, marksRestApi } from "./marks";
export { feesApi, feesRestApi } from "./fees";
export { timetableApi, timetableRestApi, DAYS, PERIODS } from "./timetable";
export { notificationsApi, notificationsRestApi } from "./notifications";
export { dashboardApi, dashboardRestApi } from "./dashboard";
export { schoolsApi, schoolsRestApi } from "./schools";
export { seedApi } from "./seed";
export { registrationsApi, superAdminApi, superAdminRestApi } from "./registrations";
export { accountApi, accountRestApi } from "./account";
